spring:
  application:
    name: contanotify
  data:
    mongodb:
      uri: mongodb://localhost:27017/contanotify
  mail:
    host: smtp.gmail.com
    port: 587
    username: contanotifytest@gmail.com
    password: ${EMAIL_PASS_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            strust:smtp.gmail.com
        debug: true
        transport:
          protocol: smtp
  activemq:
    broker-url: tcp://localhost:61616
    user: ${USER_ACTIVE_MQ}
    password: ${PASSWORD_ACTIVE_MQ}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 18000000
  #expiration-ms: 3600000   # 1 hora (puedes ajustar)

dias:
  alerta:
    urgente: 3
    alta: 7
    media: 13
    hoy: 0


